services:
  share-bib:
    image: ghcr.io/visualdust/share-bib:latest
    # build: .  # uncomment to build locally
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./data:/data
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-}
      - AUTH_TYPE=${AUTH_TYPE:-simple}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
      - OAUTH_AUTHORIZE_URL=${OAUTH_AUTHORIZE_URL:-}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL:-}
      - OAUTH_USERINFO_URL=${OAUTH_USERINFO_URL:-}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI:-}
      - OAUTH_SCOPES=${OAUTH_SCOPES:-}
      - OAUTH_ADMIN_GROUP=${OAUTH_ADMIN_GROUP:-}
    restart: unless-stopped
